coisa = input('Digite algo: ')
print(f'Tipo primitivo de {coisa}: {type(coisa)}')
print(f'Só tem espaços? {coisa.isspace()}')
print(f'É um número? {coisa.isnumeric()}')
print(f'É alfabético? {coisa.isalpha()}')
print(f'É alfanumerico? {coisa.isalnum()}')
print(f'Está em maiúsculas? {coisa.isupper()}')
print(f'Está em minúsclas? {coisa.islower()}')
print(f'Está capitalizada? {coisa.istitle()}')
